banking:
  outputs:
    dev:
      account: hub10165
      database: banking_db
      password: Burroloko_2026
      role: Banking_role
      schema: Analytics
      threads: 1
      type: snowflake
      user: Kleiton
      warehouse: banking_wh
  target: dev
